
osx_image: xcode7.1
language: objective-c
podfile: Example/Podfile

env:
  global:
    - LANG=en_US.UTF-8
    - COCOAPODS_DISABLE_DETERMINISTIC_UUIDS=true

cache:
  - bundler
  - cocoapods

script:
  - pod install --project-directory=Example
  # - scan
